# Generated by Django 6.0.1 on 2026-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['level_order']},
        ),
        migrations.RemoveField(
            model_name='floor',
            name='map_image',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='y_pos',
        ),
        migrations.AddField(
            model_name='merchant',
            name='nearest_entrance',
            field=models.CharField(blank=True, help_text='e.g. Near North Entrance / Near Cinema', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='storefront_image',
            field=models.ImageField(blank=True, null=True, upload_to='storefronts/'),
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='icon_class',
            field=models.CharField(blank=True, default='fa-store', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='lot_number',
            field=models.CharField(blank=True, help_text='e.g. G-45', max_length=50),
        ),
    ]
