# Generated by Django 6.0.1 on 2026-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_floor_options_remove_floor_map_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='accepts_ewallet',
            field=models.BooleanField(default=True, verbose_name='Accepts E-Wallet'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='instagram',
            field=models.URLField(blank=True, help_text='Full URL, e.g. https://instagram.com/shopname', null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_halal',
            field=models.BooleanField(default=False, verbose_name='Halal Certified'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords for search (hidden from user)', null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='e.g. 10:00 AM - 10:00 PM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='nearest_entrance',
            field=models.CharField(blank=True, help_text='e.g. Near North Entrance', max_length=100),
        ),
    ]
