# Generated by Django 6.0.1 on 2026-01-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_merchant_accepts_ewallet_merchant_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('monthly_fee_rm', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('featured_merchant_fee_rm', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('max_merchants', models.PositiveIntegerField(blank=True, help_text='Null means unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled')], default='TRIALING', max_length=20)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('trial_end', models.DateField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venues.plan')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='venues.venue')),
            ],
        ),
    ]

