# Generated by Django 6.0.1 on 2026-01-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_plan_venuesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('venue_type', models.CharField(blank=True, help_text='e.g. Mall, Campus, Expo', max_length=80)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
