# Generated by Django 6.0.1 on 2026-01-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_merchantupdate_merchantfollow'),
        ('merchants', '0001_initial_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='MerchantFollow'),
                migrations.DeleteModel(name='MerchantUpdate'),
                migrations.DeleteModel(name='Merchant'),
                migrations.DeleteModel(name='MerchantCategory'),
            ],
        ),
    ]

