# Generated by Django 6.0.1 on 2026-01-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0006_merchantupdate_merchantfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='MerchantCategory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('slug', models.SlugField(unique=True)),
                        ('icon_class', models.CharField(blank=True, default='fa-store', max_length=50)),
                    ],
                    options={
                        'verbose_name_plural': 'Merchant Categories',
                        'db_table': 'venues_merchantcategory',
                    },
                ),
                migrations.CreateModel(
                    name='Merchant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('lot_number', models.CharField(blank=True, help_text='e.g. G-45', max_length=50)),
                        ('nearest_entrance', models.CharField(blank=True, help_text='e.g. Near North Entrance', max_length=100)),
                        ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                        ('storefront_image', models.ImageField(blank=True, null=True, upload_to='storefronts/')),
                        ('description', models.TextField(blank=True)),
                        ('operating_hours', models.CharField(blank=True, help_text='e.g. 10:00 AM - 10:00 PM', max_length=100, null=True)),
                        ('phone_number', models.CharField(blank=True, max_length=20)),
                        ('website', models.URLField(blank=True)),
                        ('instagram', models.URLField(blank=True, help_text='Full URL, e.g. https://instagram.com/shopname', null=True)),
                        ('facebook', models.URLField(blank=True, null=True)),
                        ('is_halal', models.BooleanField(default=False, verbose_name='Halal Certified')),
                        ('accepts_ewallet', models.BooleanField(default=True, verbose_name='Accepts E-Wallet')),
                        ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for search (hidden from user)', null=True)),
                        ('is_featured', models.BooleanField(default=False)),
                        ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchants.merchantcategory')),
                        ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='venues.floor')),
                    ],
                    options={
                        'db_table': 'venues_merchant',
                    },
                ),
                migrations.CreateModel(
                    name='MerchantUpdate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=120)),
                        ('body', models.TextField(blank=True)),
                        ('link', models.URLField(blank=True)),
                        ('is_published', models.BooleanField(default=True)),
                        ('published_at', models.DateTimeField(auto_now_add=True)),
                        ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='merchants.merchant')),
                    ],
                    options={
                        'ordering': ['-published_at'],
                        'db_table': 'venues_merchantupdate',
                    },
                ),
                migrations.CreateModel(
                    name='MerchantFollow',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='merchants.merchant')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_follows', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'venues_merchantfollow',
                        'unique_together': {('user', 'merchant')},
                    },
                ),
            ],
        ),
    ]

