# Generated by Django 6.0.1 on 2026-01-12 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_productcategory_product_productimage_productvariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantfollow',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='follow_preferences', to='merchants.productcategory'),
        ),
        migrations.AddField(
            model_name='merchantfollow',
            name='notify_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantfollow',
            name='notify_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MerchantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], default='OWNER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'merchant')},
            },
        ),
    ]
