# Generated by Django 6.0.1 on 2026-01-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENUE', 'Venue owner'), ('MERCHANT', 'Merchant')], default='CUSTOMER', max_length=20),
        ),
    ]
